server:
  port: 8182

logging:
  level:
    com.project.imdang: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
