dependencies {
    implementation project(":member-service:member-service-client:member-service-client-api")
    implementation project(':common:common-domain:common-domain-core')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'com.mysql:mysql-connector-j'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign:4.1.3'
}
