dependencies {
    implementation project(":member-service:member-service-client:member-service-client-api")
    implementation project(':common:common-domain:common-domain-core')
    implementation project(':infrastructure:feign')
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign:4.1.3'
//    implementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'
}
