dependencies {
    implementation project(':insight-service:insight-domain:insight-application-service')
    implementation project(':common:common-domain:common-application-service')
    implementation project(':common:common-domain:common-domain-core')

    implementation project(':insight-service:insight-messaging:message')

    implementation 'org.springframework.boot:spring-boot-starter'
}
